[workspace]
resolver = "3"
members = ["dpop-auth"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/theterekhov/dpop-auth"

[workspace.dependencies]
sha2 = "0.11.0"
jsonwebtoken = { version = "11.0.0", features = ["aws_lc_rs"] }
base64ct = { version = "1.8.3", features = ["alloc"] }
hex = "0.4.3"
thiserror = "2.0.20"
