[package]
name = "web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.105"
leptos = {version = "0.8.20", features = ["csr"] }
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.78"
web-sys = { version = "0.3.105", features = ["Crypto", "SubtleCrypto", "CryptoKey", "CryptoKeyPair", "EcdsaParams", "EcKeyGenParams", "Window", "Headers", "Request", "RequestInit", "Response", "IdbFactory", "IdbDatabase", "IdbOpenDbRequest", "IdbTransaction", "IdbObjectStore", "IdbRequest", "IdbVersionChangeEvent", "IdbTransactionMode", "DomStringList", "Event"] }
futures-channel   = "0.3.34"
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
base64ct.workspace = true
uuid = {workspace = true, features = ["js"]}
console_error_panic_hook = "0.1.7"
