//! TOTP (2FA) enrollment, confirmation, and verification (feature `totp`).

use uuid::Uuid;

use crate::{
    ServiceError,
    crypto::totp::{
        TotpSetup, generate_recovery_codes, generate_setup, hash_recovery_code, is_recovery_code,
        setup_from_secret, verify_code,
    },
    store::{repo::totp as repo_totp, repo::users as repo_users},
};

use super::AuthService;

/// The specific category of second-factor credential verified during authentication.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SecondFactorKind {
    /// A standard time-based one-time password generated by an authenticator
    /// application (RFC 6238).
    Totp,
    /// A single-use backup recovery code that was atomically consumed and invalidated
    /// upon verification.
    RecoveryCode,
}

/// Internal classification outcome for a single TOTP evaluation attempt.
enum TotpCheck {
    /// Code matched the expected HMAC-SHA1 value within the time window
    /// and has not been used yet.
    Valid,
    /// Code did not match the expected value or was malformed.
    Invalid,
    /// Code was cryptographically valid but was already used
    /// within the current time window.
    Replayed,
}

impl AuthService {
    /// Verifies a time-based one-time password with replay protection (RFC 6238 section 5.2).
    ///
    /// Checks the code against the shared secret within the permitted time-drift window.
    /// If cryptographically valid, atomically attempts to record `(user_id, code)` into
    /// the replay cache using an entry-level lock to eliminate TOCTOU race conditions.
    ///
    /// # Returns
    ///
    /// * [`TotpCheck::Valid`] - The token is cryptographically valid, fresh,
    ///   and successfully claimed.
    /// * [`TotpCheck::Invalid`] - The code did not match the shared secret or was malformed.
    /// * [`TotpCheck::Replayed`] - The code is valid but has already been submitted within
    ///   the active window.
    ///
    /// # Errors
    ///
    /// This function returns `Ok(_)` for valid, invalid or replayed outcomes. The `Result`
    /// wrapper is retained for interface consistency with the async service pipeline.
    async fn verify_totp_once(
        &self,
        user_id: Uuid,
        secret: &str,
        code: &str,
    ) -> Result<TotpCheck, ServiceError> {
        if !verify_code(secret, code) {
            return Ok(TotpCheck::Invalid);
        }

        let key = (user_id, code.trim().to_string());

        let entry = self
            .totp_replay_cache
            .entry_by_ref(&key)
            .or_insert(())
            .await;

        if entry.is_fresh() {
            Ok(TotpCheck::Valid)
        } else {
            Ok(TotpCheck::Replayed)
        }
    }

    /// Starts (or resumes) the two-factor authentication (2FA) enrollment flow.
    ///
    /// The generated secret is placed into a temporary draft column
    /// (`totp_pending_secret`) with a 10-minute TTL and does not touch the active
    /// `totp_secret`. The draft is only promoted to the active secret upon successful code
    /// verification in [`Self::confirm_2fa`].
    ///
    /// # Idempotent Setup / Tab Refresh
    ///
    /// If a live pending draft already exists (within the 10-minute TTL), this function
    /// reconstructs and returns **same** setup data and QR code rather than generating
    /// a new secret. This allows the user to refresh or reopen the setup page without
    /// invalidating the QR code already scanned by their authenticator app.
    ///
    /// # Parameters
    ///
    /// * `user_id` - Primary key (`UUIDv7`) of the user enrolling in 2FA.
    /// * `issuer` - Provider/Service name shown in the authenticator app (e.g., `"MyApp"`).
    /// * `account_name` - User identifier shown in the authenticator app (e.g., email or username).
    ///
    /// # Errors
    ///
    /// * [`ServiceError::Unauthorized`] - The specified user does not exists or
    ///   has been soft-deleted.
    /// * [`ServiceError::Conflict`] - 2FA is already confirmed and active for this user.
    /// * [`ServiceError::Internal`] - QR code rendering, secret generation, or database operations
    ///   failed.
    pub async fn setup_2fa(
        &self,
        user_id: Uuid,
        issuer: &str,
        account_name: &str,
    ) -> Result<TotpSetup, ServiceError> {
        let mut conn = self.pool.acquire().await?;

        let user = repo_users::find_user_by_id(&mut conn, user_id)
            .await?
            .ok_or(ServiceError::Unauthorized)?;

        // Do not start a draft for an already-enrolled user: 2FA is already on,
        // there is nothing to draft. `setup_2fa` on an enrolled user writes
        // nothing (and the frontend should already show "2FA enabled").
        if user.totp_enabled {
            return Err(ServiceError::Conflict("2FA already enabled".into()));
        }

        // A live draft (within TTL) already exists: re-show the SAME QR.
        // Regenerating here would orphan the phone (its already-scanned code
        // would no longer match) and a hard `Conflict` would lock the user out
        // of the QR until the TTL expires. Returning the existing draft keeps
        // both the resume path and the already-scanned code valid.
        if let Some(existing) = repo_totp::get_pending_totp_secret(&mut conn, user_id).await? {
            return setup_from_secret(&existing, issuer, account_name)
                .map_err(|e| ServiceError::Internal(e.to_string()));
        }

        let setup = generate_setup(issuer, account_name)
            .map_err(|e| ServiceError::Internal(e.to_string()))?;

        repo_totp::set_pending_totp_secret(&mut conn, user_id, &setup.secret_base32).await?;

        Ok(setup)
    }

    /// Verifies the initial TOTP code to complete 2FA activation and issues
    /// recovery codes.
    ///
    /// Reads the pending draft secret, checks that its 10-minute TTL has not expired,
    /// and verifies the submitted `code`. Upon success, executes an atomic transaction that:
    /// 1. Promotes `totp_pending_secret` to active `totp_secret`, set `totp_enabled = TRUE`,
    ///    and clears the pending draft.
    /// 2. Invalidates any existing recovery codes previously issued for this user.
    /// 3. Stores the cryptographic hashes of 10 freshly generated recovery codes.
    ///
    /// Returns the plaintext recovery codes. **These codes are shown to the user exactly once.**
    ///
    /// # Parameters
    ///
    /// * `user_id` - Primary key (`UUIDv7`) of the user confirming 2FA.
    /// * `code` - 6-digit numeric TOTP string produced by the authenticator app.
    ///
    /// # Errors
    ///
    /// * [`ServiceError::Unauthorized`] - The user does not exist or the
    ///   submitted `code` is invalid.
    /// * [`ServiceError::Conflict`] - 2FA is already enabled, or the pending draft expired /
    ///   does not exist.
    /// * [`ServiceError::Internal`] - CSPRNG failure, database queries, or transaction
    ///   execution failed.
    pub async fn confirm_2fa(
        &self,
        user_id: Uuid,
        code: &str,
    ) -> Result<Vec<String>, ServiceError> {
        let mut conn = self.pool.acquire().await?;

        let user = repo_users::find_user_by_id(&mut conn, user_id)
            .await?
            .ok_or(ServiceError::Unauthorized)?;

        if user.totp_enabled {
            return Err(ServiceError::Conflict("2FA already enabled".into()));
        }

        // Draft + TTL check live in one place: `None` means no draft or expired.
        let Some(secret) = repo_totp::get_pending_totp_secret(&mut conn, user_id).await? else {
            return Err(ServiceError::Conflict(
                "setup expired, run setup_2fa again".into(),
            ));
        };

        if !verify_code(&secret, code) {
            return Err(ServiceError::Unauthorized);
        }

        // Propagate entropy failures instead of silently issuing empty codes.
        let recovery_codes =
            generate_recovery_codes(10).map_err(|e| ServiceError::Internal(e.to_string()))?;
        let hashes: Vec<String> = recovery_codes
            .iter()
            .map(|c| hash_recovery_code(c))
            .collect();

        // Activation + recovery codes commit together (principle 3).
        let mut tx = self.pool.begin().await?;

        repo_totp::activate_totp(&mut tx, user.id).await?;
        repo_totp::invalidate_recovery_codes_for_user(&mut tx, user.id).await?;
        repo_totp::create_recovery_codes(&mut tx, user.id, &hashes).await?;

        tx.commit().await?;

        Ok(recovery_codes)
    }

    /// Validates a second-factor credential (TOTP code or single-use recovery code)
    /// for an active user.
    ///
    /// Distinguishes between TOTP codes and recovery codes via [`crate::crypto::totp::is_recovery_code`]:
    /// * **Recovery code**: The hash is verified against `dpop_recovery_codes` scoped strictly
    ///   to `user_id`. If valid, the code immediately consumed (deleted/burned) in the database.
    /// * **TOTP Code**: Checked against RFC 6238 rules with replay protection enforced via
    ///   in-memory cache.
    ///
    /// # Parameters
    ///
    /// * `user_id` - Primary key (UUIDv7) of the user verifying the credential.
    /// * `code` - Submitted second-factor string (either a 6-digit TOTP token or an
    ///   alphanumeric recovery code).
    ///
    /// # Returns
    ///
    /// * [`SecondFactorKind::RecoveryCode`] - A single use recovery code was consumed
    ///   (caller should display a warning/remaining count).
    /// * [`SecondFactorKind::Totp`] - A standard time-based TOTP code was accepted.
    ///
    /// # Errors
    ///
    /// * [`ServiceError::Unauthorized`] - The user does not exist, the code is incorrect,
    ///   or a TOTP replay was detected.
    /// * [`ServiceError::Conflict`] - 2FA is not enabled for this user.
    /// * [`ServiceError::Internal`] - A database query or pool acquisition failed.
    pub async fn verify_2fa_code(
        &self,
        user_id: Uuid,
        code: &str,
    ) -> Result<SecondFactorKind, ServiceError> {
        let mut conn = self.pool.acquire().await?;

        let user = repo_users::find_user_by_id(&mut conn, user_id)
            .await?
            .ok_or(ServiceError::Unauthorized)?;

        if !user.totp_enabled {
            return Err(ServiceError::Conflict("2FA is not enabled".into()));
        }

        if is_recovery_code(code) {
            let hash = hash_recovery_code(code);

            // Ownership is checked inside the SQL (`WHERE user_id = $1`), so a
            // code belonging to another user is rejected without being burned.
            if repo_totp::consume_recovery_code(&mut conn, user.id, &hash)
                .await?
                .is_some()
            {
                Ok(SecondFactorKind::RecoveryCode)
            } else {
                Err(ServiceError::Unauthorized)
            }
        } else {
            let secret = user
                .totp_secret
                .as_deref()
                .ok_or(ServiceError::Unauthorized)?;

            match self.verify_totp_once(user.id, secret, code).await? {
                TotpCheck::Valid => Ok(SecondFactorKind::Totp),
                TotpCheck::Invalid | TotpCheck::Replayed => Err(ServiceError::Unauthorized),
            }
        }
    }

    /// Disables two-factor authentication for an account after verifying a step-up code.
    ///
    /// Requires a valid TOTP or recovery code to prevent unauthorized deactivation.
    /// Upon successful verification, an atomic transaction:
    /// 1. Clears `totp_secret`, resets `totp_enabled` to `FALSE`, and nullifies timestamps.
    /// 2. Permanently deletes/invalidates all remaining recovery codes for the user.
    ///
    /// # Parameters
    ///
    /// * `user_id` - Primary key (`UUIDv7`) of the user disabling 2FA.
    /// * `code` - Step-up credential (valid TOTP code or unused recovery code).
    ///
    /// # Errors
    ///
    /// * [`ServiceError::Unauthorized`] - The user does not exist or the step-up code is invalid.
    /// * [`ServiceError::Conflict`] - 2FA is not currently enabled for this user.
    /// * [`ServiceError::Internal`] - A database transaction or query failed.
    pub async fn disable_2fa(&self, user_id: Uuid, code: &str) -> Result<(), ServiceError> {
        let mut conn = self.pool.acquire().await?;

        let user = repo_users::find_user_by_id(&mut conn, user_id)
            .await?
            .ok_or(ServiceError::Unauthorized)?;

        if !user.totp_enabled {
            return Err(ServiceError::Conflict("2FA is not enabled".into()));
        }

        self.verify_2fa_code(user_id, code).await?;

        let mut tx = self.pool.begin().await?;

        repo_totp::disable_totp(&mut tx, user.id).await?;
        repo_totp::invalidate_recovery_codes_for_user(&mut tx, user.id).await?;

        tx.commit().await?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::net::{IpAddr, Ipv4Addr};

    use sqlx::PgPool;
    use totp_rs::{Algorithm, Builder, Secret};

    use crate::{
        DpopConfig, TokenSigner,
        service::RegisterParams,
        store::{models::UserRow, repo::identifiers as repo_identifiers},
    };

    use super::*;

    const JKT: &str = "0ZcOCORZNYy-DWpqq30jZyJGHTN0d2HglBV3uiguA4I";
    const PASSWORD: &str = "correct horse battery staple";

    fn test_ip() -> IpAddr {
        IpAddr::V4(Ipv4Addr::new(203, 0, 113, 7))
    }

    fn service(pool: &PgPool) -> AuthService {
        let singer = TokenSigner::symmetric(b"test-secret-key-must-be-at-least-32-bytes").unwrap();
        let config = DpopConfig::builder()
            .public_url("https://example.com")
            .signer(singer)
            .build()
            .unwrap();

        AuthService::new(pool.clone(), config)
    }

    async fn register(pool: &PgPool) -> UserRow {
        let service = service(pool);
        service
            .register(RegisterParams {
                kind: "email",
                value: "john@example.com",
                password: PASSWORD,
                name: "John",
                jkt: JKT,
                client_ip: test_ip(),
                user_agent: None,
            })
            .await
            .unwrap();

        let mut conn = pool.acquire().await.unwrap();
        repo_identifiers::find_user_by_identifier(&mut conn, "email", "john@example.com")
            .await
            .unwrap()
            .unwrap()
    }

    fn current_code(secret_base32: &str) -> String {
        let secret = Secret::try_from_base32(secret_base32).unwrap();

        Builder::new()
            .with_algorithm(Algorithm::SHA1)
            .with_secret(secret)
            .build()
            .unwrap()
            .generate_current()
            .to_string()
    }

    // Run setup + confirm for a user and return the freshly-issued recovery codes.
    async fn enroll(pool: &PgPool, user_id: Uuid) -> Vec<String> {
        let service = service(pool);
        let setup = service
            .setup_2fa(user_id, "Example", "john@example.com")
            .await
            .unwrap();
        let code = current_code(&setup.secret_base32);

        service.confirm_2fa(user_id, &code).await.unwrap()
    }

    #[sqlx::test]
    async fn setup_confirms_then_activates_2fa(pool: PgPool) {
        let user = register(&pool).await;
        let service = service(&pool);

        // Phase 1: setup writes ONLY a pending draft, not the active secret.
        let setup = service
            .setup_2fa(user.id, "Example", "john@example.com")
            .await
            .unwrap();
        assert!(!setup.secret_base32.is_empty());

        let mut conn = pool.acquire().await.unwrap();

        let before = repo_users::find_user_by_id(&mut conn, user.id)
            .await
            .unwrap()
            .unwrap();
        assert!(!before.totp_enabled);
        assert!(
            before.totp_secret.is_none(),
            "active secret untouched by setup"
        );

        // Phase 2+3: confirm verifies the draft + TTL, then activates atomically.
        let code = current_code(&setup.secret_base32);
        let recovery_codes = service.confirm_2fa(user.id, &code).await.unwrap();

        assert_eq!(recovery_codes.len(), 10);
        assert!(recovery_codes.iter().all(|c| is_recovery_code(c)));

        let enabled = repo_users::find_user_by_id(&mut conn, user.id)
            .await
            .unwrap()
            .unwrap();
        assert!(enabled.totp_enabled);
        assert!(enabled.totp_enabled_at.is_some());
        assert_eq!(
            enabled.totp_secret.as_deref(),
            Some(&setup.secret_base32[..])
        );
        assert!(
            enabled.totp_pending_secret.is_none(),
            "pending secret cleared after activation"
        );
    }

    #[sqlx::test]
    async fn confirm_2fa_rejects_wrong_code(pool: PgPool) {
        let user = register(&pool).await;
        let service = service(&pool);

        service
            .setup_2fa(user.id, "Example", "john@example.com")
            .await
            .unwrap();
        assert!(matches!(
            service.confirm_2fa(user.id, "000000").await,
            Err(ServiceError::Unauthorized)
        ));

        let mut conn = pool.acquire().await.unwrap();

        let after = repo_users::find_user_by_id(&mut conn, user.id)
            .await
            .unwrap()
            .unwrap();
        assert!(!after.totp_enabled, "wrong code must not activate 2FA");
        assert!(after.totp_secret.is_none());
    }

    #[sqlx::test]
    async fn expired_draft_is_rejected(pool: PgPool) {
        let user = register(&pool).await;
        let service = service(&pool);

        let setup = service
            .setup_2fa(user.id, "Example", "john@example.com")
            .await
            .unwrap();

        // Age the draft past the 10-minutes TTL directly in the DB.
        // Use an owner connection and drop it BEFORE calling confirm_2fa
        // (which acquires its own connection) - this avoids holding a pool slot
        // and any risk of pool exhaustion with a small `#[sqlx::test]` pool.
        {
            let mut conn = pool.acquire().await.unwrap();

            sqlx::query!(
                r#"
     	UPDATE dpop_users
      	SET totp_pending_at = now() - INTERVAL '11 minutes'
       	WHERE id = $1
     	"#,
                user.id
            )
            .execute(&mut *conn)
            .await
            .unwrap();
        } // conn dropped here

        let code = current_code(&setup.secret_base32);
        assert!(matches!(
            service.confirm_2fa(user.id, &code).await,
            Err(ServiceError::Conflict(_))
        ));

        let mut conn = pool.acquire().await.unwrap();

        let after = repo_users::find_user_by_id(&mut conn, user.id)
            .await
            .unwrap()
            .unwrap();
        assert!(!after.totp_enabled, "expired draft must not activate");
        assert!(after.totp_secret.is_none());
        assert!(after.totp_pending_secret.is_some());
        assert!(after.totp_pending_at.is_some());
    }

    #[sqlx::test]
    async fn setup_2fa_returns_same_live_draft(pool: PgPool) {
        let user = register(&pool).await;
        let service = service(&pool);

        let first = service
            .setup_2fa(user.id, "Example", "john@example.com")
            .await
            .unwrap();
        let second = service
            .setup_2fa(user.id, "Example", "john@example.com")
            .await
            .unwrap();

        // A live draft (younger than TTL) is *resumed*, not replaced and not
        // blocked: the Same secret comes back, so a refreshed tab (F5) recovers
        // the QR the phone already scanned instead of failing with `Conflict.`
        assert_eq!(second.secret_base32, first.secret_base32);

        // The re-shown QR / draft is still valid for confirmation.
        let code = current_code(&second.secret_base32);
        let recovery_codes = service.confirm_2fa(user.id, &code).await.unwrap();
        assert_eq!(recovery_codes.len(), 10);
    }

    #[sqlx::test]
    async fn verify_2fa_code_rejects_replay(pool: PgPool) {
        let user = register(&pool).await;
        let service = service(&pool);

        let recovery_codes = enroll(&pool, user.id).await;
        assert_eq!(recovery_codes.len(), 10);

        // The step-up code must be generated from the ACTIVE secret,
        // not a fresh draft: `setup_2fa` on an enrolled user writes nothing.
        let mut conn = pool.acquire().await.unwrap();

        let active_secret = repo_users::find_user_by_id(&mut conn, user.id)
            .await
            .unwrap()
            .unwrap()
            .totp_secret
            .clone()
            .unwrap();

        drop(conn);

        let step_up = current_code(&active_secret);
        assert_eq!(
            service.verify_2fa_code(user.id, &step_up).await.unwrap(),
            SecondFactorKind::Totp
        );
        assert!(matches!(
            service.verify_2fa_code(user.id, &step_up).await,
            Err(ServiceError::Unauthorized)
        ));
    }

    #[sqlx::test]
    async fn recovery_code_is_single_use(pool: PgPool) {
        let user = register(&pool).await;
        let service = service(&pool);

        let recovery_codes = enroll(&pool, user.id).await;
        assert_eq!(recovery_codes.len(), 10);

        let used = service
            .verify_2fa_code(user.id, &recovery_codes[0])
            .await
            .unwrap();
        assert_eq!(used, SecondFactorKind::RecoveryCode);

        let again = service.verify_2fa_code(user.id, &recovery_codes[0]).await;
        assert!(matches!(again, Err(ServiceError::Unauthorized)));
    }

    #[sqlx::test]
    async fn disable_2fa_clears_state(pool: PgPool) {
        let user = register(&pool).await;
        let service = service(&pool);

        let recovery_codes = enroll(&pool, user.id).await;

        service
            .disable_2fa(user.id, &recovery_codes[0])
            .await
            .unwrap();

        let mut conn = pool.acquire().await.unwrap();

        let updated_user = repo_users::find_user_by_id(&mut conn, user.id)
            .await
            .unwrap()
            .unwrap();

        assert!(!updated_user.totp_enabled);
        assert!(updated_user.totp_secret.is_none());
        assert!(updated_user.totp_pending_secret.is_none());

        let active_recovery_codes = repo_totp::count_active_recovery_codes(&mut conn, user.id)
            .await
            .unwrap();
        assert_eq!(active_recovery_codes, 0);
    }
}
